contact_links:
  - name: Request a new feature
    url: https://github.com/LostPaul/obsidian-folder-overview/discussions/
    about: Instead of creating a new issue for feature requests, use the discussions feature instead