name: Plugin Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: true

permissions:
  contents: write  # Allow write access to repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to access all tags and branches

      - name: Fetch all remote branches
        run: git fetch --all

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV

      - name: Run fv-build
        run: |
          npm install
          npm run fv-build

      # Debug step to check if files exist after build
      - name: Check if built files exist
        run: |
          ls -la src/obsidian-folder-overview/

      - name: Prepare files for release
        run: |
          mkdir -p release
          cp src/obsidian-folder-overview/main.js src/obsidian-folder-overview/styles.css manifest.json release/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release/main.js,release/styles.css,release/manifest.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: Remove built files from main branch
        run: |
          git checkout main  # Checkout the main branch
          git rm -f src/obsidian-folder-overview/main.js src/obsidian-folder-overview/styles.css  # Remove the files
          git commit -m "Remove main.js and styles.css after release" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/LostPaul/obsidian-folder-overview.git HEAD:main  # Push the change to main
