name: Build and Push to Folder Overview

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout folder-notes
        uses: actions/checkout@v3
        with:
          repository: LostPaul/obsidian-folder-notes
          fetch-depth: 0
          submodules: recursive
          path: folder-notes  # Ensures it's in the correct folder

      - name: Run npm install in folder-notes
        run: |
          cd folder-notes
          npm install

      - name: Run fv-build in folder-notes
        run: |
          cd folder-notes
          npm run fv-build

      - name: Check built files
        run: |
          ls -la folder-notes/src/obsidian-folder-overview/

      - name: Checkout folder-overview
        uses: actions/checkout@v3
        with:
          repository: LostPaul/obsidian-folder-overview
          token: ${{ secrets.PAT }}
          path: folder-overview

      - name: Copy built files to folder-overview
        run: |
          cp folder-notes/src/obsidian-folder-overview/main.js folder-notes/src/obsidian-folder-overview/styles.css folder-overview/

      - name: Commit and push built files
        run: |
          cd folder-overview
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add main.js styles.css
          git commit -m "Add built files for release"
          git push origin main

      - name: Trigger release workflow in folder-overview
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/LostPaul/obsidian-folder-overview/actions/workflows/release.yml/dispatches \
          -d '{"ref": "main", "inputs": {"tag": "${{ github.ref_name }}"}}'
