name: Trigger Folder Notes Build

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build on folder-notes
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/LostPaul/obsidian-folder-notes/actions/workflows/build-and-push.yml/dispatches \
          -d '{"ref": "main", "inputs": {"tag": "${{ github.ref_name }}"}}'
