name: Trigger Build in Folder Notes

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in folder-notes
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/LostPaul/obsidian-folder-notes/actions/workflows/create-release-for-fv.yaml/dispatches \
          -d '{"ref": "main", "inputs": {"tag": "${{ github.ref_name }}"}}'
